preload = /home/ls/Pictures/wallpaper/amex/platinum.jpg
preload = /home/ls/Pictures/wallpaper/linux/arch/wifu.png
preload = /home/ls/Pictures/wallpaper/chess.com/neonPieces.png

wallpaper = DP-2, /home/ls/Pictures/wallpaper/chess.com/neonPieces.png
wallpaper = DVI-D-1, /home/ls/Pictures/wallpaper/amex/platinum.jpg


wallpaper_mode = cover

