preload = /home/ls/Pictures/wallpaper/amex/platinum.jpg
preload = /home/ls/Pictures/wallpaper/linux/arch/wifu.png



wallpaper = DP-2, /home/ls/Pictures/wallpaper/linux/arch/wifu.png
wallpaper = DVI-D-1, /home/ls/Pictures/wallpaper/amex/platinum.jpg


wallpaper_mode = cover

