# American Express Wallpaper
preload = /home/ls/Pictures/wallpaper/amex/owncard.jpg
preload = /home/ls/Pictures/wallpaper/amex/background.jpg
preload = /home/ls/Pictures/wallpaper/amex/wood.jpg

# Linux Themed Wallpaper
preload = /home/ls/Pictures/wallpaper/linux/arch/wifu.png

# Chess themed Wallpaper
preload = /home/ls/Pictures/wallpaper/chess.com/neonPieces.png

wallpaper {
    monitor = DP-2
    path = /home/ls/Pictures/wallpaper/chess.com/neonPieces.png
    fit_mode = cover
}

wallpaper {
    monitor = DVI-D-1
    path = /home/ls/Pictures/wallpaper/amex/owncard.jpg
    fit_mode = cover
}
