[WebService]
Origins = https://ip-adress:9090 wss://ip-adress:9090 https://computername:9090 wss://computername:9090 https://subdomain.domain.tld wss://subdomain.domain.tld
ProtocolHeader = X-Forwarded-Proto
AllowUnencrypted = true ip-adress


